use super::*;

/// Copied from `mise lock --platform macos-arm64,linux-x64` output of mise 2026.10.3 (conda
/// dependency lists shortened, one entry with an unknown field and one second options variant
/// added, as a newer mise might write).
const REAL: &str = r#"# @generated - this file is auto-generated by `mise lock` https://mise.jdx.dev/dev-tools/mise-lock.html

lockfile_version = 3

[conda-packages.macos-arm64."libpq-17.6-h31f7a3a_2"]
url = "https://conda.anaconda.org/conda-forge/osx-arm64/libpq-17.6-h31f7a3a_2.conda"
checksum = "sha256:f1098a2f0e1b5e8b9a0f6f3c1b0f3a1e8a1c35b3e2b1d6f9e8d7c6b5a4f3e2d1"

[conda-packages.macos-arm64."openssl-3.6.5-h5503f6c_0"]
url = "https://conda.anaconda.org/conda-forge/osx-arm64/openssl-3.6.5-h5503f6c_0.conda"
checksum = "sha256:a3cbe2f7b4dd9c1e2a6f3e4b7c8d9e0f1a2b3c4d5e6f708192a3b4c5d6e7f809"

[[tools.fnox]]
version = "1.39.0"
backend = "packslip:github.com/jdx/fnox"
specifiers = ["1.39.0"]

[tools.fnox."platforms.linux-x64"]
checksum = "sha256:0a623ed38907b9cb633d07593b4d19a4ba741a6a50d226eb243bd16f2f5ba81b"
url = "https://github.com/jdx/fnox/releases/download/v1.39.0/fnox-x86_64-unknown-linux-gnu.tar.gz"
signer = "sigstore-oidc:https://github.com/jdx/fnox/.github/workflows/release.yml"
repository_ids = { repository = "1078762196" }

[tools.fnox."platforms.macos-arm64"]
checksum = "sha256:5604196e7a0aafb949251be1ae088bf0bb524edbfb45748d1be0cbc46e98b8f5"
url = "https://github.com/jdx/fnox/releases/download/v1.39.0/fnox-aarch64-apple-darwin.tar.gz"
signer = "sigstore-oidc:https://github.com/jdx/fnox/.github/workflows/release.yml"
repository_ids = { repository = "1078762196" }

[[tools.jq]]
version = "1.7.1"
backend = "aqua:jqlang/jq"
specifiers = ["1.7.1"]
future_field = "a newer mise wrote this"

[tools.jq."platforms.linux-x64"]
checksum = "sha256:5942c9b0934e510ee61eb3e30273f1b3fe2590df93933a93d7c58b81d19c8ff5"
url = "https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-amd64"
url_api = "https://api.github.com/repos/jqlang/jq/releases/assets/140520984"

[tools.jq."platforms.macos-arm64"]
checksum = "sha256:0bbe619e663e0de2c550be2fe0d240d076799d6f8a652b70fa04aea8a8362e8a"
url = "https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-macos-arm64"
url_api = "https://api.github.com/repos/jqlang/jq/releases/assets/140521010"

[[tools."npm:prettier"]]
version = "3.6.2"
aube = { path = "locks/npm-prettier/3.6.2", digest = "sha256:0b89746a30f01583c5a61188214359640173b1a970950f998712393f23f4252d" }
backend = "npm:prettier"
specifiers = ["3.6.2"]

[[tools.postgres]]
version = "17.6"
backend = "conda:postgresql"
specifiers = ["17.6"]

[tools.postgres.options]
channel = "conda-forge"

[tools.postgres."platforms.macos-arm64"]
checksum = "sha256:37d520f883ab5ce7a834df33e467adb17b04df1205e8830a3839f065f7615ecc"
url = "https://conda.anaconda.org/conda-forge/osx-arm64/postgresql-17.6-hb74d643_2.conda"
conda_deps = [
    "libpq-17.6-h31f7a3a_2",
    "openssl-3.6.5-h5503f6c_0",
]

[[tools.python]]
version = "3.13.2"
backend = "core:python"
specifiers = ["3.13.2"]

[tools.python."platforms.linux-x64"]
checksum = "sha256:ee909a9d0fb16375ebd3b3ca0322fd9cac0904b304e28ad68527036858e301e9"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20250317/cpython-3.13.2+20250317-x86_64-unknown-linux-gnu-install_only_stripped.tar.gz"
provenance = "github-attestations"

[tools.python."platforms.macos-arm64"]
checksum = "sha256:9002e620e4113e7439b2de0db5ff9b2dc914cde4fba2f10134cce3a5cdebac81"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20250317/cpython-3.13.2+20250317-aarch64-apple-darwin-install_only_stripped.tar.gz"
provenance = "github-attestations"

[[tools.rust]]
version = "1.93.1"
backend = "core:rust"
specifiers = ["1.93.1"]

[[tools.swift]]
version = "6.1"
backend = "core:swift"
specifiers = ["6.1"]

[tools.swift.options]
swift_platform = "ubuntu22.04"

[[tools.swift]]
version = "6.1"
backend = "core:swift"
specifiers = ["6.1"]

[tools.swift.options]
swift_platform = "ubuntu24.04"
"#;

fn pin(tool: &str, version: &str) -> PinKey {
    PinKey { tool: tool.into(), version: version.into() }
}

fn real_pins() -> Vec<PinKey> {
    vec![
        pin("fnox", "1.39.0"),
        pin("jq", "1.7.1"),
        pin("npm:prettier", "3.6.2"),
        pin("postgres", "17.6"),
        pin("python", "3.13.2"),
        pin("rust", "1.93.1"),
        pin("swift", "6.1"),
    ]
}

fn platforms(list: &[&str]) -> Vec<String> {
    list.iter().map(|p| p.to_string()).collect()
}

fn captured() -> (Table, Vec<PinKey>) {
    capture(REAL).unwrap()
}

#[test]
fn render_and_capture_are_inverses_on_real_output() {
    let (lock, stripped) = captured();
    assert_eq!(stripped, [pin("npm:prettier", "3.6.2")], "the npm sidecar reference is stripped");
    let embedded = finish(lock.clone(), None, stripped, &real_pins(), &platforms(&["macos-arm64", "linux-x64"]));
    assert_eq!(embedded.keys().next().map(String::as_str), Some("provider"));
    let rendered = render(&embedded);
    let (again, none) = capture(&rendered).unwrap();
    assert!(none.is_empty());
    assert_eq!(again, lock, "render then capture gives the captured lock back");
    // Everything but the sidecar reference survives, compared as parsed documents.
    let mut original: Table = toml::from_str(REAL).unwrap();
    original["tools"]["npm:prettier"][0].as_table_mut().unwrap().remove("aube");
    assert_eq!(to_mise(&embedded), original);
    assert!(!rendered.contains("aube") && !rendered.contains("stack_sidecars") && !rendered.contains("provider ="), "{rendered}");
    let doc: Table = toml::from_str(&rendered).unwrap();
    assert_eq!(doc["tools"]["swift"].as_array().unwrap().len(), 2, "both options variants of one version are kept");
    assert_eq!(doc["tools"]["jq"][0]["future_field"].as_str(), Some("a newer mise wrote this"));
    assert_eq!(doc["tools"]["fnox"][0]["platforms.macos-arm64"]["repository_ids"]["repository"].as_str(), Some("1078762196"));
    assert!(doc["tools"]["jq"][0]["platforms.macos-arm64"]["url_api"].is_str());
    // And it survives stack.lock's own serialization.
    let lock_file = crate::lock::Lockfile { provider_lock: Some(embedded.clone()), ..crate::lock::Lockfile::new(vec![], vec![], vec![]) };
    let text = toml::to_string_pretty(&lock_file).unwrap();
    let back: crate::lock::Lockfile = toml::from_str(&text).unwrap();
    assert_eq!(back.provider_lock.as_ref(), Some(&embedded));
}

#[test]
fn coverage_follows_the_backend_and_the_platform_entry() {
    let (lock, stripped) = captured();
    let embedded = finish(lock, None, stripped, &real_pins(), &platforms(&["macos-arm64", "linux-x64"]));
    let state = |tool: &str, version: &str, platform: &str| coverage(Some(&embedded), &pin(tool, version), platform).state;
    assert_eq!(state("fnox", "1.39.0", "macos-arm64"), State::Verified);
    assert_eq!(state("jq", "1.7.1", "linux-x64"), State::Verified);
    assert_eq!(state("python", "3.13.2", "macos-arm64"), State::Verified);
    assert_eq!(state("postgres", "17.6", "macos-arm64"), State::Verified);
    assert_eq!(state("postgres", "17.6", "linux-x64"), State::Missing, "no entry for the platform");
    assert_eq!(state("jq", "1.7.1", "macos-x64"), State::Missing);
    assert_eq!(state("jq", "1.8.0", "linux-x64"), State::Missing, "another version");
    assert_eq!(state("rust", "1.93.1", "linux-arm64"), State::Exempt);
    assert_eq!(state("npm:prettier", "3.6.2", "macos-arm64"), State::Unsupported);
    // Unlocked releases are classified by the name when it names a backend.
    assert_eq!(coverage(None, &pin("cargo:ripgrep", "14.1.0"), "linux-x64").state, State::Exempt);
    assert_eq!(coverage(None, &pin("pipx:black", "24.1.0"), "linux-x64").state, State::Unsupported);
    assert_eq!(coverage(None, &pin("vfox:nodejs", "20.0.0"), "linux-x64").state, State::Missing, "plain vfox records URLs");
    let c = coverage(Some(&embedded), &pin("fnox", "1.39.0"), "macos-arm64");
    assert_eq!(c.checksum.as_deref(), Some("sha256:5604196e7a0aafb949251be1ae088bf0bb524edbfb45748d1be0cbc46e98b8f5"));
    assert!(c.signer.unwrap().starts_with("sigstore-oidc:"));

    // A packslip entry without its signer is not called verified; nor is a URL without checksum.
    let mut weak = embedded.clone();
    weak["tools"]["fnox"][0]["platforms.macos-arm64"].as_table_mut().unwrap().remove("signer");
    weak["tools"]["jq"][0]["platforms.linux-x64"].as_table_mut().unwrap().remove("checksum");
    assert_eq!(coverage(Some(&weak), &pin("fnox", "1.39.0"), "macos-arm64").state, State::Missing);
    assert_eq!(coverage(Some(&weak), &pin("jq", "1.7.1"), "linux-x64").state, State::Missing);

    // An unusual backend that carried a sidecar stays unsupported after the reference is gone.
    let custom = "[[tools.mytool]]\nversion = \"1.0.0\"\nbackend = \"vfox-custom:mytool\"\nsidecar = { path = \"locks/x\", digest = \"sha256:00\" }\n";
    let (lock, stripped) = capture(custom).unwrap();
    assert_eq!(stripped, [pin("mytool", "1.0.0")]);
    let embedded = finish(lock, None, stripped, &[pin("mytool", "1.0.0")], &platforms(&["linux-x64"]));
    let text = toml::to_string(&embedded).unwrap();
    let back: Table = toml::from_str(&text).unwrap();
    assert_eq!(coverage(Some(&back), &pin("mytool", "1.0.0"), "linux-x64").state, State::Unsupported);
    assert!(!render(&back).contains("sidecar"));
}

#[test]
fn partitions_keep_every_version_of_a_name_together() {
    let (lock, stripped) = captured();
    let embedded = finish(lock, None, stripped, &real_pins(), &platforms(&["macos-arm64", "linux-x64"]));
    let pins = vec![pin("jq", "1.7.1"), pin("rust", "1.93.1"), pin("npm:prettier", "3.6.2"), pin("postgres", "17.6"), pin("postgres", "16.4"), pin("fnox", "1.39.0")];
    let p = partition(Some(&embedded), &pins, "macos-arm64");
    assert_eq!(p.locked, ["jq", "rust", "fnox"]);
    assert_eq!(p.plain, ["npm:prettier", "postgres"], "postgres@16.4 is missing, so the name goes plain");
    let s = summary(Some(&embedded), &pins, "macos-arm64");
    assert_eq!(s.verified, ["jq@1.7.1", "postgres@17.6", "fnox@1.39.0"]);
    assert_eq!((s.exempt.len(), s.unsupported.len(), s.missing.clone()), (1, 1, vec!["postgres@16.4".to_string()]));
    let empty = partition(None, &[], "macos-arm64");
    assert!(empty.locked.is_empty() && empty.plain.is_empty());
}

#[test]
fn validation_names_entries_that_disagree_with_pins_and_dangling_dependencies() {
    let (lock, stripped) = captured();
    let embedded = finish(lock, None, stripped, &real_pins(), &platforms(&["macos-arm64", "linux-x64"]));
    validate(&embedded, &real_pins()).unwrap();
    let mut pins = real_pins();
    pins.retain(|p| p.tool != "jq");
    pins.push(pin("jq", "1.8.0"));
    let e = validate(&embedded, &pins).unwrap_err();
    assert_eq!(e.code, "lock_invalid");
    assert!(e.message.contains("tools.jq") && e.message.contains("1.7.1"), "{e:?}");
    let mut dangling = embedded.clone();
    dangling["conda-packages"]["macos-arm64"].as_table_mut().unwrap().remove("openssl-3.6.5-h5503f6c_0");
    let e = validate(&dangling, &real_pins()).unwrap_err();
    assert_eq!(e.code, "lock_invalid");
    assert_eq!(e.details[0]["dep"], "openssl-3.6.5-h5503f6c_0", "{e:?}");
}

#[test]
fn retain_drops_unpinned_entries_unlisted_platforms_and_unreferenced_records() {
    let (lock, stripped) = captured();
    let mut embedded = finish(lock, None, stripped, &real_pins(), &platforms(&["macos-arm64", "linux-x64"]));
    let pins = vec![pin("jq", "1.7.1"), pin("postgres", "17.6")];
    retain(&mut embedded, &pins, &platforms(&["linux-x64"]));
    let tools = embedded["tools"].as_table().unwrap();
    assert_eq!(tools.keys().collect::<Vec<_>>(), ["jq", "postgres"]);
    assert!(tools["jq"][0].get("platforms.macos-arm64").is_none() && tools["jq"][0].get("platforms.linux-x64").is_some());
    assert!(embedded.get("conda-packages").is_none(), "macos-arm64 records go with the platform");
    assert!(embedded.get("stack_sidecars").is_none(), "npm:prettier is no longer pinned");
}

fn merge(committed: Option<&Table>, fresh: &str, targets: &[&str], pins: &[PinKey], update: bool, reasons: &Reasons) -> Result<Merged> {
    let (fresh, _) = capture(fresh).unwrap();
    let targets: BTreeSet<String> = targets.iter().map(|t| t.to_string()).collect();
    Merge { committed, fresh, targets: &targets, pins, platforms: &platforms(&["macos-arm64", "linux-x64"]), update, reasons, changed: &BTreeSet::new() }.run()
}

const JQ_FRESH: &str = r#"lockfile_version = 3
[[tools.jq]]
version = "1.7.1"
backend = "aqua:jqlang/jq"
specifiers = ["1.7.1"]
[tools.jq."platforms.linux-x64"]
checksum = "sha256:ffff"
url = "https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-amd64"
[tools.jq."platforms.macos-arm64"]
checksum = "sha256:0bbe619e663e0de2c550be2fe0d240d076799d6f8a652b70fa04aea8a8362e8a"
url = "https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-macos-arm64"
url_api = "https://api.github.com/repos/jqlang/jq/releases/assets/140521010"
"#;

#[test]
fn ordinary_merges_keep_committed_values_and_report_differences() {
    let (committed, _) = captured();
    let pins = real_pins();
    let m = merge(Some(&committed), JQ_FRESH, &["jq"], &pins, false, &Reasons::new()).unwrap();
    let jq = &m.lock["tools"]["jq"][0];
    assert_eq!(jq["platforms.linux-x64"]["checksum"].as_str(), Some("sha256:5942c9b0934e510ee61eb3e30273f1b3fe2590df93933a93d7c58b81d19c8ff5"), "committed checksum kept");
    assert_eq!(jq["future_field"].as_str(), Some("a newer mise wrote this"), "unknown fields of the committed entry kept");
    assert!(m.warnings.iter().any(|w| w == "artifacts.jq@1.7.1.linux-x64 differs upstream; run `stack compile --update` to accept"), "{:?}", m.warnings);
    assert_eq!(m.events[&(pin("jq", "1.7.1"), "linux-x64".into())].change, Some("differs_upstream"));
    // Pins not named for locking keep their committed entries byte for byte.
    assert_eq!(m.lock["tools"]["fnox"], committed["tools"]["fnox"]);
    assert_eq!(m.lock["conda-packages"], committed["conda-packages"]);
}

#[test]
fn update_merges_accept_changes_and_never_report_a_skipped_refresh_as_one() {
    let (committed, _) = captured();
    let pins = real_pins();
    let m = merge(Some(&committed), JQ_FRESH, &["jq"], &pins, true, &Reasons::new()).unwrap();
    let jq = &m.lock["tools"]["jq"][0];
    assert_eq!(jq["platforms.linux-x64"]["checksum"].as_str(), Some("sha256:ffff"));
    let e = &m.events[&(pin("jq", "1.7.1"), "linux-x64".into())];
    assert_eq!(e.change, Some("artifact_changed"));
    assert_eq!(e.checksum_was.as_deref(), Some("sha256:5942c9b0934e510ee61eb3e30273f1b3fe2590df93933a93d7c58b81d19c8ff5"));
    assert!(e.url_was.is_some());
    assert!(!m.events.contains_key(&(pin("jq", "1.7.1"), "macos-arm64".into())), "an unchanged value is not reported");

    // Offline: mise keeps no entry for jq (the seed had none), exits 0, and says nothing.
    let m = merge(Some(&committed), "lockfile_version = 3\n", &["jq"], &pins, true, &Reasons::new()).unwrap();
    assert_eq!(m.lock["tools"]["jq"][0]["platforms.linux-x64"], committed["tools"]["jq"][0]["platforms.linux-x64"]);
    for platform in ["linux-x64", "macos-arm64"] {
        let e = &m.events[&(pin("jq", "1.7.1"), platform.into())];
        assert_eq!(e.change, Some("retained"), "{platform}");
        assert!(e.reason.as_deref().unwrap().contains("committed value is kept"));
    }
    // A platform the fresh entry lacks is retained with mise's reason.
    let partial = JQ_FRESH.split("[tools.jq.\"platforms.macos-arm64\"]").next().unwrap();
    let reasons: Reasons = [(("jq".to_string(), "macos-arm64".to_string()), "failed to resolve jq for macos-arm64: offline".to_string())].into();
    let m = merge(Some(&committed), partial, &["jq"], &pins, true, &reasons).unwrap();
    let e = &m.events[&(pin("jq", "1.7.1"), "macos-arm64".into())];
    assert_eq!((e.change, e.reason.as_deref()), (Some("retained"), Some("failed to resolve jq for macos-arm64: offline")));
    assert!(m.lock["tools"]["jq"][0].get("platforms.macos-arm64").is_some());
}

const PG_FRESH: &str = r#"lockfile_version = 3
[[tools.postgres]]
version = "17.6"
backend = "conda:postgresql"
specifiers = ["17.6"]
[tools.postgres.options]
channel = "conda-forge"
[tools.postgres."platforms.macos-arm64"]
checksum = "sha256:37d520f883ab5ce7a834df33e467adb17b04df1205e8830a3839f065f7615ecc"
url = "https://conda.anaconda.org/conda-forge/osx-arm64/postgresql-17.6-hb74d643_2.conda"
conda_deps = ["libpq-17.6-h31f7a3a_2", "openssl-3.6.5-h5503f6c_0"]
[conda-packages.macos-arm64."libpq-17.6-h31f7a3a_2"]
url = "https://conda.anaconda.org/conda-forge/osx-arm64/libpq-17.6-h31f7a3a_2.conda"
checksum = "sha256:f1098a2f0e1b5e8b9a0f6f3c1b0f3a1e8a1c35b3e2b1d6f9e8d7c6b5a4f3e2d1"
[conda-packages.macos-arm64."openssl-3.6.5-h5503f6c_0"]
url = "https://conda.anaconda.org/conda-forge/osx-arm64/openssl-3.6.5-h5503f6c_0.conda"
checksum = "sha256:changed"
[conda-packages.macos-arm64."unreferenced-1.0-0"]
url = "https://conda.anaconda.org/conda-forge/osx-arm64/unreferenced-1.0-0.conda"
checksum = "sha256:0000"
"#;

#[test]
fn shared_dependency_records_are_kept_unless_updated_and_unreferenced_ones_pruned() {
    let (committed, _) = captured();
    let pins = real_pins();
    let m = merge(Some(&committed), PG_FRESH, &["postgres"], &pins, false, &Reasons::new()).unwrap();
    let conda = &m.lock["conda-packages"]["macos-arm64"];
    assert_eq!(conda["openssl-3.6.5-h5503f6c_0"], committed["conda-packages"]["macos-arm64"]["openssl-3.6.5-h5503f6c_0"]);
    assert!(conda.get("unreferenced-1.0-0").is_none(), "pruned");
    assert!(m.warnings.iter().any(|w| w.contains("conda-packages.macos-arm64.openssl-3.6.5-h5503f6c_0 differs upstream")), "{:?}", m.warnings);
    let deps = &m.events[&(pin("postgres", "17.6"), "macos-arm64".into())].deps;
    assert_eq!(deps[0]["dep"], "openssl-3.6.5-h5503f6c_0");
    assert_eq!(deps[0]["change"], "differs_upstream");

    let m = merge(Some(&committed), PG_FRESH, &["postgres"], &pins, true, &Reasons::new()).unwrap();
    assert_eq!(m.lock["conda-packages"]["macos-arm64"]["openssl-3.6.5-h5503f6c_0"]["checksum"].as_str(), Some("sha256:changed"));
    let deps = &m.events[&(pin("postgres", "17.6"), "macos-arm64".into())].deps;
    assert_eq!((deps[0]["change"].as_str(), deps[0]["checksum_was"].as_str()), (Some("artifact_changed"), Some("sha256:a3cbe2f7b4dd9c1e2a6f3e4b7c8d9e0f1a2b3c4d5e6f708192a3b4c5d6e7f809")));

    // A fresh entry whose dependency has no record anywhere is lock_invalid.
    let dangling = PG_FRESH.replace("conda_deps = [\"libpq-17.6-h31f7a3a_2\", \"openssl-3.6.5-h5503f6c_0\"]", "conda_deps = [\"libpq-17.6-h31f7a3a_2\", \"zlib-9-0\"]");
    let e = merge(None, &dangling, &["postgres"], &pins, false, &Reasons::new()).err().unwrap();
    assert_eq!(e.code, "lock_invalid");
    assert!(e.message.contains("zlib-9-0"), "{e:?}");
}

#[test]
fn unknown_top_level_tables_take_minses_latest_value_and_survive_otherwise() {
    let mut committed = captured().0;
    committed.insert("tool-stubs".into(), Value::Array(vec![Value::String("a".into())]));
    committed.insert("future_table".into(), toml::from_str::<Table>("x = 1").unwrap().into());
    let fresh = JQ_FRESH.replace("lockfile_version = 3\n", "lockfile_version = 3\ntool-stubs = [\"b\"]\n");
    let m = merge(Some(&committed), &fresh, &["jq"], &real_pins(), false, &Reasons::new()).unwrap();
    assert_eq!(m.lock["tool-stubs"], Value::Array(vec![Value::String("b".into())]));
    assert_eq!(m.lock["future_table"]["x"].as_integer(), Some(1));
}

#[test]
fn targets_are_pins_with_missing_coverage_or_everything_under_update() {
    let (lock, stripped) = captured();
    let embedded = finish(lock, None, stripped, &real_pins(), &platforms(&["macos-arm64", "linux-x64"]));
    let two = platforms(&["macos-arm64", "linux-x64"]);
    let t = targets(Some(&embedded), &real_pins(), &two, false, &BTreeSet::new());
    // postgres has no linux-x64 entry; the rest are covered, exempt (rust, swift) or
    // unsupported (npm).
    assert_eq!(t.into_iter().collect::<Vec<_>>(), ["postgres"]);
    assert_eq!(targets(Some(&embedded), &real_pins(), &two, true, &BTreeSet::new()).len(), 7);
    assert_eq!(targets(Some(&embedded), &[pin("jq", "1.7.1")], &platforms(&["linux-arm64"]), false, &BTreeSet::new()).len(), 1, "a newly listed platform");
}

#[test]
fn changed_pins_are_targeted_when_their_checked_entry_was_locked_for_another_request() {
    let (lock, stripped) = captured();
    let two = platforms(&["macos-arm64", "linux-x64"]);
    let embedded = finish(lock, None, stripped, &real_pins(), &two);
    // jq is verified on both platforms and rust is exempt: neither is a target until changed,
    // and an exempt pin has no checked entry to reconcile even then.
    let changed: BTreeSet<PinKey> = [pin("jq", "1.7.1"), pin("rust", "1.93.1")].into();
    let t = targets(Some(&embedded), &real_pins(), &two, false, &changed);
    assert_eq!(t.into_iter().collect::<Vec<_>>(), ["jq", "postgres"]);
}

#[test]
fn a_pin_changes_with_its_options_or_release_but_not_with_its_request_alone() {
    use crate::lock::{LockedVersion, Lockfile};
    use crate::tool::OptionValue;
    let version = |name: &str, tool: Option<&str>, requested: &str, resolved: &str, identity: Option<&str>| {
        let mut options = crate::tool::ToolOptions::new();
        if let Some(id) = identity {
            options.insert("identity".into(), OptionValue::String(id.into()));
        }
        LockedVersion { name: name.into(), tool: tool.map(Into::into), requested: requested.into(), resolved: resolved.into(), resolved_on: None, options }
    };
    let lock = |tools: Vec<LockedVersion>, services: Vec<LockedVersion>| Lockfile::new(vec![], tools, services);
    let before = lock(vec![version("fnox", None, "1.39.0", "1.39.0", Some("old")), version("jq", None, "1.7", "1.7.1", None)], vec![version("db", Some("postgres"), "17", "17.6", None)]);
    assert!(changed_pins(Some(&before), &before).is_empty());
    // The same releases asked for differently, and a tool that duplicates a service's pin.
    let same = lock(
        vec![version("fnox", None, "1.39", "1.39.0", Some("old")), version("jq", None, "1.7.1", "1.7.1", None), version("postgres", None, "17.6", "17.6", None)],
        vec![version("db", Some("postgres"), "17.6", "17.6", None)],
    );
    assert!(changed_pins(Some(&before), &same).is_empty());
    let options = lock(vec![version("fnox", None, "1.39.0", "1.39.0", Some("new")), version("jq", None, "1.7", "1.7.1", None)], vec![version("db", Some("postgres"), "17", "17.6", None)]);
    assert_eq!(changed_pins(Some(&before), &options).into_iter().collect::<Vec<_>>(), [pin("fnox", "1.39.0")]);
    let release = lock(vec![version("fnox", None, "1.39.0", "1.39.0", Some("old")), version("jq", None, "1.7", "1.7.1", None)], vec![version("db", Some("postgres"), "17", "17.7", None)]);
    assert_eq!(changed_pins(Some(&before), &release).into_iter().collect::<Vec<_>>(), [pin("postgres", "17.7")]);
    assert_eq!(changed_pins(None, &before).len(), 3);
}

#[test]
fn a_changed_pin_without_a_fresh_value_is_retained_and_said_to_be() {
    let (committed, _) = captured();
    let targets: BTreeSet<String> = ["jq".to_string()].into();
    let changed: BTreeSet<PinKey> = [pin("jq", "1.7.1")].into();
    let (fresh, _) = capture("lockfile_version = 3\n").unwrap();
    let pins = real_pins();
    let m = Merge { committed: Some(&committed), fresh, targets: &targets, pins: &pins, platforms: &platforms(&["macos-arm64", "linux-x64"]), update: false, reasons: &Reasons::new(), changed: &changed }.run().unwrap();
    assert_eq!(m.lock["tools"]["jq"], committed["tools"]["jq"], "the commitment is kept");
    for platform in ["macos-arm64", "linux-x64"] {
        assert_eq!(m.events[&(pin("jq", "1.7.1"), platform.into())].change, Some("retained"), "{platform}");
        assert!(m.warnings.contains(&format!("artifacts.jq@1.7.1.{platform}: its request changed, but mise produced no fresh entry to compare; the committed value is kept")), "{:?}", m.warnings);
    }
    // An unchanged pin without a fresh value is simply kept, as before.
    let (fresh, _) = capture("lockfile_version = 3\n").unwrap();
    let m = Merge { committed: Some(&committed), fresh, targets: &targets, pins: &pins, platforms: &platforms(&["macos-arm64", "linux-x64"]), update: false, reasons: &Reasons::new(), changed: &BTreeSet::new() }.run().unwrap();
    assert!(m.events.is_empty() && m.warnings.is_empty());
}

#[test]
fn reasons_come_from_minses_lines_naming_tool_and_platform() {
    let stderr = "mise lock            redis@8.2.1 linux-x64\nmise ERROR failed to resolve redis for linux-arm64: failed to solve redis-server for linux-arm64\nfailed to resolve redis for macos-arm64: failed to solve redis-server for macos-arm64 (version 8.2.1)\nmise lock          ✓ 3 platform entries\n";
    let tools: BTreeSet<String> = ["redis".to_string(), "jq".to_string()].into();
    let r = reasons(stderr, &tools, &platforms(&["linux-x64", "linux-arm64", "macos-arm64"]));
    assert_eq!(r.len(), 2, "{r:?}");
    assert_eq!(r[&("redis".into(), "linux-arm64".into())], "failed to resolve redis for linux-arm64: failed to solve redis-server for linux-arm64");
    assert!(r[&("redis".into(), "macos-arm64".into())].ends_with("(version 8.2.1)"));
}

#[test]
fn seeds_carry_only_tools_not_being_locked() {
    let (committed, _) = captured();
    let targets: BTreeSet<String> = ["jq".to_string(), "postgres".to_string()].into();
    let seed = seed(Some(&committed), &targets, &platforms(&["macos-arm64", "linux-x64"]));
    let doc: Table = toml::from_str(&seed).unwrap();
    assert_eq!(doc.keys().next().map(String::as_str), Some("lockfile_version"));
    assert!(doc["tools"].get("jq").is_none() && doc["tools"].get("postgres").is_none());
    assert!(doc["tools"].get("fnox").is_some());
    assert!(doc.get("conda-packages").is_none(), "records only postgres referenced are not seeded");
    assert_eq!(toml::from_str::<Table>(&super::seed(None, &targets, &[])).unwrap()["lockfile_version"].as_integer(), Some(3));
}

#[test]
fn platform_names_are_mises() {
    assert_eq!(platform_of("macos", "aarch64"), "macos-arm64");
    assert_eq!(platform_of("linux", "x86_64"), "linux-x64");
    assert_eq!(canonical_platform("macos-aarch64"), "macos-arm64");
    assert_eq!(canonical_platform("linux-x86_64"), "linux-x64");
    assert_eq!(canonical_platform("linux-x64"), "linux-x64");
    assert!(valid_platform(&current_platform()), "{}", current_platform());
    for ok in ["macos-arm64", "linux-x64-musl", "linux-arm64-musl-baseline", "windows-x64", "linux-riscv64"] {
        assert!(valid_platform(ok), "{ok}");
    }
    for bad in ["darwin-arm64", "linux-amd64", "macos", "linux-x64-alpine", "current", ""] {
        assert!(!valid_platform(bad), "{bad}");
    }
}

#[test]
fn policy_defaults_to_the_release_matrix_and_validates_names() {
    use crate::manifest::LockSettings;
    let p = Policy::from_settings(&LockSettings::default()).unwrap();
    assert_eq!(p.platforms, DEFAULT_PLATFORMS);
    assert!(!p.required());
    let p = Policy::from_settings(&LockSettings { platforms: Some(vec!["current".into(), "linux-x64".into(), "linux-x64".into()]), artifacts: Some("required".into()) }).unwrap();
    assert!(p.required());
    assert_eq!(p.platforms[0], current_platform());
    assert_eq!(p.platforms.iter().filter(|x| *x == "linux-x64").count(), 1);
    for bad in [
        LockSettings { platforms: Some(vec!["macos-aarch64".into()]), artifacts: None },
        LockSettings { platforms: Some(vec![]), artifacts: None },
        LockSettings { platforms: None, artifacts: Some("strict".into()) },
    ] {
        assert_eq!(Policy::from_settings(&bad).unwrap_err().code, "manifest_invalid");
    }
}

#[test]
fn required_policies_refuse_an_unlisted_runtime_platform_and_best_effort_ones_never_do() {
    use crate::manifest::LockSettings;
    let required = Policy::from_settings(&LockSettings { platforms: Some(vec!["linux-x64".into()]), artifacts: Some("required".into()) }).unwrap();
    required.check_platform("linux-x64").unwrap();
    let e = required.check_platform("macos-arm64").unwrap_err();
    assert_eq!(e.code, "artifact_unlocked");
    assert!(e.message.contains("macos-arm64") && e.message.contains("linux-x64"), "{e:?}");
    assert_eq!(e.details, vec![json!({ "platform": "macos-arm64", "state": "unlisted", "platforms": ["linux-x64"] })]);
    let best_effort = Policy::from_settings(&LockSettings { platforms: Some(vec!["linux-x64".into()]), artifacts: None }).unwrap();
    best_effort.check_platform("macos-arm64").unwrap();
    // `current` always lists the machine it was expanded on.
    let current = Policy::from_settings(&LockSettings { platforms: Some(vec!["current".into()]), artifacts: Some("required".into()) }).unwrap();
    current.check_runtime_platform().unwrap();
}

#[test]
fn rendering_writes_only_with_entries_and_removes_a_stale_file() {
    let dir = tempfile::tempdir().unwrap();
    let (lock, stripped) = captured();
    let embedded = finish(lock, None, stripped, &real_pins(), &platforms(&["macos-arm64"]));
    let mut file = crate::lock::Lockfile::new(vec![], vec![], vec![]);
    file.provider_lock = Some(embedded);
    write_rendered(dir.path(), Some(&file)).unwrap();
    let path = rendered_path(dir.path());
    assert!(std::fs::read_to_string(&path).unwrap().starts_with("# Generated by stack"));
    file.provider_lock = None;
    write_rendered(dir.path(), Some(&file)).unwrap();
    assert!(!path.exists());
    write_rendered(dir.path(), None).unwrap();
}
