//! A fake `mise lock` that writes the keys mise 2026.9.18 and 2026.10.3 write: for core:bun,
//! an unqualified `--platform` also writes Bun's build variants (`platform_variants` in
//! src/plugins/core/bun.rs); every other backend writes the requested key only. Tables for
//! bun 1.3.0 and node 24.13.0 are the ones real mise 2026.10.3 wrote (captured on macos-arm64,
//! `mise lock --platform linux-x64,linux-x64-musl,macos-arm64,macos-x64`); anything else gets a
//! synthetic table. Kept independent of stack's own variant table on purpose.

#![allow(dead_code)]

use stack::error::StackError;
use stack::lock;
use stack::project::{compile, Options, Report};
use stack::provider::mise::{CalVer, LockRun, Locker, Resolver, ScratchRoot};
use stack::source::Mode;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};
use tempfile::TempDir;
use toml::{Table, Value};

/// `mise lock` 2026.10.3 output for bun 1.3.0, verbatim.
pub const REAL_BUN: &str = r#"# @generated - this file is auto-generated by `mise lock` https://mise.jdx.dev/dev-tools/mise-lock.html

lockfile_version = 3

[[tools.bun]]
version = "1.3.0"
backend = "core:bun"
specifiers = ["1.3.0"]

[tools.bun."platforms.linux-x64"]
checksum = "sha256:60c39d92b8bd090627524c98b3012f0c08dc89024cfdaa7c9c98cb5fd4359376"
url = "https://github.com/oven-sh/bun/releases/download/bun-v1.3.0/bun-linux-x64.zip"

[tools.bun."platforms.linux-x64-baseline"]
checksum = "sha256:77336611905b9e876e52924f8b1a57e72669cf10541dc1e11269d2c9371f9e45"
url = "https://github.com/oven-sh/bun/releases/download/bun-v1.3.0/bun-linux-x64-baseline.zip"

[tools.bun."platforms.linux-x64-musl"]
checksum = "sha256:cb6fad19a68c8984fcda815f8d53850c17349a7ccdc882343c4e1eb0846129e6"
url = "https://github.com/oven-sh/bun/releases/download/bun-v1.3.0/bun-linux-x64-musl.zip"

[tools.bun."platforms.linux-x64-musl-baseline"]
checksum = "sha256:73d5bf04d079e53fd1d4d0839d9d027d8bafa643a1a1da772b8df0c0bad35be0"
url = "https://github.com/oven-sh/bun/releases/download/bun-v1.3.0/bun-linux-x64-musl-baseline.zip"

[tools.bun."platforms.macos-arm64"]
checksum = "sha256:85848e3f96481efcabe75a500fd3b94b9bb95686ab7ad0a3892976c7be15036a"
url = "https://github.com/oven-sh/bun/releases/download/bun-v1.3.0/bun-darwin-aarch64.zip"

[tools.bun."platforms.macos-x64"]
checksum = "sha256:09d54af86ec45354bb63ff7ccc3ce9520d74f4e45f9f7cac8ceb7fac422fcc19"
url = "https://github.com/oven-sh/bun/releases/download/bun-v1.3.0/bun-darwin-x64.zip"

[tools.bun."platforms.macos-x64-baseline"]
checksum = "sha256:45619502b426357d375c59f18606ea4ca2c2d59428c86f4429950a1cfee86a15"
url = "https://github.com/oven-sh/bun/releases/download/bun-v1.3.0/bun-darwin-x64-baseline.zip"
"#;

/// `mise lock` 2026.10.3 output for node 24.13.0 with `linux-x64-musl` requested explicitly;
/// requesting `linux-x64` alone writes no musl table for Node.
pub const REAL_NODE: &str = r#"# @generated - this file is auto-generated by `mise lock` https://mise.jdx.dev/dev-tools/mise-lock.html

lockfile_version = 3

[[tools.node]]
version = "24.13.0"
backend = "core:node"
specifiers = ["24.13.0"]

[tools.node."platforms.linux-x64"]
checksum = "sha256:6223aad1a81f9d1e7b682c59d12e2de233f7b4c37475cd40d1c89c42b737ffa8"
url = "https://nodejs.org/dist/v24.13.0/node-v24.13.0-linux-x64.tar.gz"

[tools.node."platforms.linux-x64-musl"]
checksum = "sha256:e2750d9e00008d2eadcecc00e17c3060980ed26888de90a55f9873ebdcde74ac"
url = "https://unofficial-builds.nodejs.org/download/release/v24.13.0/node-v24.13.0-linux-x64-musl.tar.gz"

[tools.node."platforms.macos-arm64"]
checksum = "sha256:d595961e563fcae057d4a0fb992f175a54d97fcc4a14dc2d474d92ddeea3b9f8"
url = "https://nodejs.org/dist/v24.13.0/node-v24.13.0-darwin-arm64.tar.gz"
"#;

pub struct Upstream;

impl Resolver for Upstream {
    fn resolve(&self, _tool: &str, request: &str) -> Result<String, StackError> {
        Ok(request.into())
    }

    fn registry_backend(&self, _tool: &str) -> Result<Option<String>, StackError> {
        Ok(None)
    }
}

#[derive(Debug, Clone)]
pub struct Call {
    pub tools: Vec<String>,
    pub platforms: Vec<String>,
    pub seed: String,
}

pub struct FakeMise {
    /// Keys whose table "upstream" now serves with a different checksum.
    pub changed: Mutex<Vec<String>>,
    /// Keys mise produced nothing for this time (offline, or not published).
    pub unpublished: Mutex<Vec<String>>,
    pub calls: Mutex<Vec<Call>>,
}

impl FakeMise {
    pub fn new() -> Arc<Self> {
        Arc::new(Self { changed: Mutex::new(vec![]), unpublished: Mutex::new(vec![]), calls: Mutex::new(vec![]) })
    }

    pub fn calls(&self) -> Vec<Call> {
        self.calls.lock().unwrap().clone()
    }

    /// The keys mise writes for one requested platform.
    fn written(tool: &str, platform: &str) -> Vec<String> {
        let qualified = platform.splitn(3, '-').nth(2).is_some();
        let variants: &[&str] = match (tool, platform) {
            ("bun", _) if qualified => &[],
            ("bun", "linux-x64") => &["baseline", "musl", "musl-baseline"],
            ("bun", "linux-arm64") => &["musl"],
            ("bun", "macos-x64") | ("bun", "windows-x64") => &["baseline"],
            _ => &[],
        };
        std::iter::once(platform.to_string()).chain(variants.iter().map(|v| format!("{platform}-{v}"))).collect()
    }

    fn table(&self, tool: &str, version: &str, key: &str) -> Option<Value> {
        if self.unpublished.lock().unwrap().iter().any(|k| k == key) {
            return None;
        }
        let real = match (tool, version) {
            ("bun", "1.3.0") => Some(REAL_BUN),
            ("node", "24.13.0") => Some(REAL_NODE),
            _ => None,
        };
        let mut table = real
            .and_then(|text| toml::from_str::<Table>(text).ok())
            .and_then(|lock| lock["tools"][tool][0].get(format!("platforms.{key}")).cloned())
            .unwrap_or_else(|| {
                let mut t = Table::new();
                t.insert("checksum".into(), format!("sha256:{tool}-{version}-{key}").into());
                t.insert("url".into(), format!("https://example.invalid/{tool}/{version}/{key}").into());
                t.into()
            });
        if self.changed.lock().unwrap().iter().any(|k| k == key) {
            table.as_table_mut().unwrap().insert("checksum".into(), format!("sha256:upstream-changed-{key}").into());
        }
        Some(table)
    }
}

impl Locker for FakeMise {
    fn version(&self, _: &Path) -> Result<CalVer, StackError> {
        Ok(CalVer(2026, 10, 3))
    }

    fn lock(&self, scratch: &ScratchRoot, platforms: &[String], tools: &[String]) -> Result<LockRun, StackError> {
        let lock_path = scratch.path().join(".config/mise/mise.lock");
        let seed = fs::read_to_string(&lock_path).unwrap();
        let config: Table = toml::from_str(&fs::read_to_string(scratch.config_path()).unwrap()).unwrap();
        self.calls.lock().unwrap().push(Call { tools: tools.into(), platforms: platforms.into(), seed: seed.clone() });
        let mut lock: Table = toml::from_str(&seed).unwrap();
        let mut stderr = String::new();
        for tool in tools {
            let version = match &config["tools"][tool.as_str()] {
                Value::String(s) => s.clone(),
                Value::Table(t) => t["version"].as_str().unwrap().into(),
                other => panic!("{other}"),
            };
            let mut entry = Table::new();
            entry.insert("version".into(), version.clone().into());
            entry.insert("backend".into(), format!("core:{tool}").into());
            entry.insert("specifiers".into(), Value::Array(vec![version.clone().into()]));
            for platform in platforms {
                for key in Self::written(tool, platform) {
                    match self.table(tool, &version, &key) {
                        Some(t) => {
                            entry.insert(format!("platforms.{key}"), t);
                        }
                        None => stderr.push_str(&format!("mise WARN  failed to lock {tool}@{version} for {key}: not available\n")),
                    }
                }
            }
            let tools = lock.entry("tools").or_insert_with(|| Table::new().into()).as_table_mut().unwrap();
            tools.insert(tool.clone(), Value::Array(vec![entry.into()]));
        }
        fs::write(&lock_path, toml::to_string_pretty(&lock).unwrap()).unwrap();
        Ok(LockRun { exit_code: Some(0), stderr })
    }
}

pub struct Sandbox {
    pub tmp: TempDir,
    pub locker: Arc<dyn Locker>,
}

impl Sandbox {
    pub fn new(stack_toml: &str, locker: Arc<dyn Locker>) -> Self {
        let sb = Self { tmp: TempDir::new().unwrap(), locker };
        fs::create_dir_all(sb.root()).unwrap();
        sb.write(stack_toml);
        sb
    }

    pub fn root(&self) -> PathBuf {
        self.tmp.path().join("app")
    }

    pub fn write(&self, stack_toml: &str) {
        fs::write(self.root().join("stack.toml"), stack_toml).unwrap();
    }

    pub fn compile(&self, mode: Mode) -> Result<Report, StackError> {
        compile(&Options {
            root: self.root(),
            mode,
            write: true,
            cache: self.tmp.path().join("cache"),
            state: self.tmp.path().join("state"),
            reassign_ports: false,
            resolver: Some(Arc::new(Upstream)),
            locker: Some(self.locker.clone()),
        })
    }

    pub fn lock(&self) -> lock::Lockfile {
        lock::read(&self.root()).unwrap().unwrap()
    }

    pub fn embedded(&self) -> Table {
        self.lock().provider_lock.unwrap()
    }

    pub fn rendered(&self) -> String {
        fs::read_to_string(self.root().join(".config/mise/mise.lock")).unwrap()
    }
}

/// The platform keys an embedded entry holds, sorted.
pub fn keys(embedded: &Table, tool: &str) -> Vec<String> {
    let mut out: Vec<String> = embedded["tools"][tool][0].as_table().unwrap().keys().filter_map(|k| k.strip_prefix("platforms.")).map(str::to_string).collect();
    out.sort();
    out
}

pub fn checksum(embedded: &Table, tool: &str, key: &str) -> String {
    embedded["tools"][tool][0][format!("platforms.{key}").as_str()]["checksum"].as_str().unwrap().into()
}

/// The checksum real mise wrote for `key`.
pub fn real(text: &str, tool: &str, key: &str) -> String {
    let lock: Table = toml::from_str(text).unwrap();
    lock["tools"][tool][0][format!("platforms.{key}").as_str()]["checksum"].as_str().unwrap().into()
}
