//! Keeping the files stack generates in a checkout out of version control.
//!
//! In a git work tree, stack lists what it generates in a `.gitignore` of its own beside it:
//! `.config/mise/.gitignore` names the provider config (`conf.d/stack.toml`), the rendered lock
//! (`mise.lock`) and mise's `locks/`; `<skills dir>/.gitignore` names `.stack-skills.json` and
//! each link stack recorded there; `.stack/.gitignore` ignores everything in `.stack/`. Each
//! names itself too, so it never shows up as untracked, and each holds exact paths, so nothing
//! else in those directories (a mise config or a skill of the user's) is ignored. A tracked
//! file stays tracked.
//!
//! A `.gitignore` covers its own checkout only. `info/exclude` cannot: git reads one for the
//! repository, shared by the main checkout and every linked worktree, so a path generated in one
//! would be ignored where it is the user's in another. Earlier releases kept a block per
//! checkout there; [`update`] removes every such block (under git's own `exclude.lock`), so what
//! they hid in other checkouts shows up again.
//!
//! A `.gitignore` stack did not write (it lacks stack's first line) or that is not a regular
//! file is never changed: stack warns about the generated paths it leaves unignored instead.

use std::io::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::{Duration, Instant};

/// The first line of every `.gitignore` stack writes, and how it knows one is its own.
const HEADER: &str = "# Generated by stack: its generated files in this directory. Do not edit.";
/// The block markers earlier releases wrote into `info/exclude`.
const BEGIN: &str = "# stack: generated files of ";
const END: &str = "# stack: end of ";
/// How long to wait for another writer's `info/exclude.lock`.
const LOCK_WAIT: Duration = Duration::from_secs(5);

/// Bring this checkout's ignore files up to date for `skills_dir` (`[skills] dir` as written).
/// Outside a git work tree nothing happens. Returns a warning when something could not be
/// written or a generated path is left unignored; generating files never fails because of it.
pub fn update(root: &Path, skills_dir: Option<&str>) -> Option<String> {
    let exclude = locate(root)?;
    let mut warnings = Vec::new();
    warnings.extend(drop_shared_blocks(&exclude));
    let mise = root.join(".config/mise");
    let generated = [".config/mise/conf.d/stack.toml", ".config/mise/mise.lock", ".config/mise/locks"];
    if generated.iter().any(|p| std::fs::symlink_metadata(root.join(p)).is_ok()) {
        warnings.extend(own(root, &mise, &["conf.d/stack.toml", "mise.lock", "locks/"].map(String::from)));
    }
    if root.join(".stack").is_dir() {
        let ignore = root.join(".stack/.gitignore");
        if std::fs::symlink_metadata(&ignore).is_err() {
            if let Err(e) = std::fs::write(&ignore, "*\n") {
                warnings.push(format!("cannot write {}: {e}", ignore.display()));
            }
        }
    }
    // A directory stack would refuse to link into holds nothing of stack's. Its normalized form
    // (`./a//b` is `a/b`) is where the links are.
    if let Some(dir) = skills_dir.and_then(|dir| crate::skills::validate_dir(dir).ok()) {
        let dir = root.join(dir);
        let links = crate::skills::linked(&dir);
        let registry = std::fs::symlink_metadata(dir.join(crate::skills::REGISTRY)).is_ok();
        let mut entries: Vec<String> = Vec::new();
        if registry {
            entries.push(crate::skills::REGISTRY.to_string());
        }
        entries.extend(links);
        warnings.extend(own(root, &dir, &entries));
    }
    (!warnings.is_empty()).then(|| warnings.join("; "))
}

/// The exclude file git reads for `root`'s repository, when `root` is in a work tree.
fn locate(root: &Path) -> Option<PathBuf> {
    let mut command = Command::new("git");
    command.arg("-C").arg(root).args(["rev-parse", "--is-inside-work-tree", "--git-path", "info/exclude"]).env("GIT_TERMINAL_PROMPT", "0");
    let out = crate::process::output(&mut command).ok().filter(|o| o.status.success())?;
    let text = String::from_utf8(out.stdout).ok()?;
    let mut lines = text.lines();
    if lines.next()? != "true" {
        return None;
    }
    Some(root.join(lines.next()?))
}

/// The `.gitignore` stack keeps in `dir`: `entries` (relative to `dir`) and itself, or none at
/// all when there are no entries. A file that is not stack's is left alone; the warning then
/// names the entries that exist and git does not ignore.
fn own(root: &Path, dir: &Path, entries: &[String]) -> Option<String> {
    let path = dir.join(".gitignore");
    let ours = match std::fs::symlink_metadata(&path) {
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => true,
        Err(e) => return Some(format!("cannot inspect {}: {e}", path.display())),
        Ok(meta) => meta.is_file() && std::fs::read_to_string(&path).is_ok_and(|text| text.lines().next() == Some(HEADER)),
    };
    if !ours {
        return unignored(root, dir, entries, &path);
    }
    if entries.is_empty() {
        return match std::fs::remove_file(&path) {
            Err(e) if e.kind() != std::io::ErrorKind::NotFound => Some(format!("cannot remove {}: {e}", path.display())),
            _ => None,
        };
    }
    let next = contents(entries);
    if std::fs::read_to_string(&path).ok().as_deref() == Some(next.as_str()) {
        return None;
    }
    write(&path, &next).err().map(|e| format!("cannot write {}: {e}; stack's generated files there are not ignored by git", path.display()))
}

/// Stack's `.gitignore` for `entries`: anchored, escaped, itself first.
fn contents(entries: &[String]) -> String {
    let mut out = format!("{HEADER}\n/.gitignore\n");
    for entry in entries {
        // A directory entry keeps its trailing `/`, so it matches the directory only.
        let (name, slash) = entry.strip_suffix('/').map_or((entry.as_str(), ""), |n| (n, "/"));
        out.push_str(&format!("/{}{slash}\n", escape(name)));
    }
    out
}

/// The `entries` of `dir` that exist and that git does not ignore, as a warning naming
/// `ignore` (a `.gitignore` stack did not write).
fn unignored(root: &Path, dir: &Path, entries: &[String], ignore: &Path) -> Option<String> {
    let present: Vec<PathBuf> = entries
        .iter()
        .map(|e| dir.join(e.trim_end_matches('/')))
        .filter(|p| std::fs::symlink_metadata(p).is_ok())
        .collect();
    if present.is_empty() {
        return None;
    }
    let mut command = Command::new("git");
    command.arg("-C").arg(root).args(["check-ignore", "--no-index", "--"]).args(&present).env("GIT_TERMINAL_PROMPT", "0");
    // Exit 1 with nothing printed: none is ignored. Anything else unreadable: assume none is.
    let ignored: Vec<PathBuf> = crate::process::output(&mut command)
        .ok()
        .filter(|o| o.status.code() == Some(0) || o.status.code() == Some(1))
        .map(|o| String::from_utf8_lossy(&o.stdout).lines().map(|l| root.join(l)).collect())
        .unwrap_or_default();
    let left: Vec<String> = present
        .iter()
        .filter(|p| !ignored.iter().any(|i| same(i, p)))
        .map(|p| p.strip_prefix(dir).unwrap_or(p).display().to_string())
        .collect();
    (!left.is_empty()).then(|| {
        format!("{} is not stack's, so stack did not add its generated {} there; add them to keep them out of git", ignore.display(), left.join(", "))
    })
}

fn same(a: &Path, b: &Path) -> bool {
    a == b || a.canonicalize().ok().zip(b.canonicalize().ok()).is_some_and(|(a, b)| a == b)
}

/// A name as a gitignore pattern that matches it literally.
fn escape(path: &str) -> String {
    let mut out = String::with_capacity(path.len());
    for c in path.chars() {
        if matches!(c, '*' | '?' | '[' | ']' | '\\') {
            out.push('\\');
        }
        out.push(c);
    }
    // Trailing spaces are dropped unless escaped.
    let kept = out.trim_end_matches(' ').len();
    let spaces = out.len() - kept;
    out.truncate(kept);
    out.push_str(&"\\ ".repeat(spaces));
    out
}

/// Remove the blocks earlier releases kept in the shared `exclude`, everything else unchanged,
/// following git's lock-file protocol: write `exclude.lock` (created exclusively, so one writer
/// at a time, git included) and rename it over `exclude`.
fn drop_shared_blocks(exclude: &Path) -> Option<String> {
    match std::fs::read_to_string(exclude) {
        Ok(text) if text.lines().any(|l| l.starts_with(BEGIN)) => {}
        Ok(_) => return None,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return None,
        Err(e) => return Some(format!("cannot read {}: {e}", exclude.display())),
    }
    let failed = |e: std::io::Error| Some(format!("cannot remove stack's old blocks from {}: {e}", exclude.display()));
    let lock = exclude.with_file_name("exclude.lock");
    let started = Instant::now();
    let mut file = loop {
        match std::fs::OpenOptions::new().write(true).create_new(true).open(&lock) {
            Ok(file) => break file,
            Err(e) if e.kind() == std::io::ErrorKind::AlreadyExists && started.elapsed() < LOCK_WAIT => {
                std::thread::sleep(Duration::from_millis(10));
            }
            Err(e) => return failed(e),
        }
    };
    let held = LockFile(&lock);
    // Read again under the lock: another writer may have changed it.
    let text = match std::fs::read_to_string(exclude) {
        Ok(text) => text,
        Err(e) => return failed(e),
    };
    let next = without_blocks(&text);
    if next == text {
        return None;
    }
    let written = (|| {
        file.write_all(next.as_bytes())?;
        if let Ok(meta) = std::fs::metadata(exclude) {
            std::fs::set_permissions(&lock, meta.permissions())?;
        }
        file.sync_all()?;
        std::fs::rename(&lock, exclude)
    })();
    match written {
        Ok(()) => {
            std::mem::forget(held);
            None
        }
        Err(e) => failed(e),
    }
}

/// Removes the lock file it names when dropped (when the rename did not consume it).
struct LockFile<'a>(&'a Path);

impl Drop for LockFile<'_> {
    fn drop(&mut self) {
        let _ = std::fs::remove_file(self.0);
    }
}

/// `text` without stack's blocks and the blank line written before each. A block without its
/// end line is kept: its lines may be the user's.
fn without_blocks(text: &str) -> String {
    let mut kept: Vec<&str> = Vec::new();
    let mut block: Option<(String, Vec<&str>)> = None;
    for line in text.lines() {
        if let Some((name, lines)) = &mut block {
            lines.push(line);
            if line == format!("{END}{name}") {
                block = None;
                if kept.last().is_some_and(|l| l.is_empty()) {
                    kept.pop();
                }
            }
            continue;
        }
        match line.strip_prefix(BEGIN) {
            Some(name) => block = Some((name.to_string(), vec![line])),
            None => kept.push(line),
        }
    }
    if let Some((_, lines)) = block {
        kept.extend(lines);
    }
    let mut out = kept.join("\n");
    if !out.is_empty() {
        out.push('\n');
    }
    out
}

/// Replace `path` whole, so a reader never sees half a file.
fn write(path: &Path, text: &str) -> std::io::Result<()> {
    let dir = path.parent().ok_or_else(|| std::io::Error::other("no parent directory"))?;
    let mut tmp = tempfile::NamedTempFile::new_in(dir)?;
    tmp.write_all(text.as_bytes())?;
    #[cfg(unix)]
    std::fs::set_permissions(tmp.path(), std::os::unix::fs::PermissionsExt::from_mode(0o644))?;
    tmp.persist(path).map_err(|e| e.error)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn stacks_gitignore_names_itself_and_exact_escaped_entries() {
        let entries = [".stack-skills.json", "jq", "a*b?[c]\\ ", "locks/"].map(String::from);
        assert_eq!(
            contents(&entries),
            format!("{HEADER}\n/.gitignore\n/.stack-skills.json\n/jq\n/a\\*b\\?\\[c\\]\\\\\\ \n/locks/\n")
        );
    }

    #[test]
    fn old_blocks_are_removed_with_their_blank_line_and_everything_else_is_kept() {
        let user = "# git ls-files --others --exclude-from=.git/info/exclude\n*.log\n";
        let text = format!("{user}\n{BEGIN}/w/app\n/app/.stack/\n{END}/w/app\n\n{BEGIN}/w/other\n/x\n{END}/w/other\nmine\n");
        assert_eq!(without_blocks(&text), format!("{user}mine\n"));
        assert_eq!(without_blocks(&format!("{BEGIN}/w/app\n/x\n{END}/w/app\n")), "");
        assert_eq!(without_blocks(user), user, "nothing of stack's: unchanged");
        // Unterminated: not provably stack's to the end, so kept.
        let open = format!("a\n{BEGIN}/w/app\n/x\nlater\n");
        assert_eq!(without_blocks(&open), open);
    }

    #[test]
    fn a_users_gitignore_is_never_changed_and_stacks_own_is_rewritten_or_removed() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        let path = root.join(".gitignore");
        let entries = ["a".to_string()];
        assert_eq!(own(root, root, &entries), None);
        assert_eq!(std::fs::read_to_string(&path).unwrap(), contents(&entries));
        let more = ["a".to_string(), "b".to_string()];
        own(root, root, &more);
        assert_eq!(std::fs::read_to_string(&path).unwrap(), contents(&more));
        own(root, root, &[]);
        assert!(!path.exists(), "nothing left to ignore: stack's file goes");
        // The user's: unchanged, whatever stack would list.
        std::fs::write(&path, "mine\n").unwrap();
        own(root, root, &more);
        own(root, root, &[]);
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "mine\n");
    }
}
