use crate::error::{io_error, Result, StackError};
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;

pub const LOCK_FILE: &str = "stack.lock";
const LOCK_VERSION: u32 = 1;

/// Exactly which bundle contents a project was compiled from.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Lockfile {
    pub version: u32,
    #[serde(default, rename = "bundle")]
    pub bundles: Vec<LockedBundle>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LockedBundle {
    /// The `[[use]] bundle` string as written in stack.toml.
    pub source: String,
    pub name: String,
    /// Resolved commit for git sources. Tags and branches never re-resolve without `--update`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub commit: Option<String>,
    /// Resolved manifest digest for OCI sources.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub digest: Option<String>,
    pub content_hash: String,
}

impl Lockfile {
    pub fn new(bundles: Vec<LockedBundle>) -> Self {
        Self {
            version: LOCK_VERSION,
            bundles,
        }
    }

    pub fn find(&self, source: &str) -> Option<&LockedBundle> {
        self.bundles.iter().find(|b| b.source == source)
    }
}

pub fn read(root: &Path) -> Result<Option<Lockfile>> {
    let path = root.join(LOCK_FILE);
    if !path.exists() {
        return Ok(None);
    }
    let text = fs::read_to_string(&path).map_err(|e| io_error(path.display(), e))?;
    let lock: Lockfile = toml::from_str(&text)
        .map_err(|e| StackError::new("lock_invalid", format!("{LOCK_FILE}: {}", e.message())))?;
    if lock.version != LOCK_VERSION {
        return Err(StackError::new(
            "lock_invalid",
            format!("unsupported {LOCK_FILE} version {}", lock.version),
        ));
    }
    Ok(Some(lock))
}

pub fn write(root: &Path, lock: &Lockfile) -> Result<()> {
    let path = root.join(LOCK_FILE);
    let body = toml::to_string_pretty(lock).expect("lockfile serializes");
    let text = format!("# Generated by `stack compile`. Commit this file.\n{body}");
    fs::write(&path, text).map_err(|e| io_error(path.display(), e))
}
