//! Scratch provider roots: a private mise configuration that names exact tools and nothing else.
//!
//! Version resolution, artifact locking and skills discovery ask mise about releases without
//! touching the project. Each call gets a root of its own under the cache
//! (`<cache>/<purpose>/<random>/`), removed when the [`ScratchRoot`] is dropped, success or
//! not, so concurrent commands never share one. Its only configuration is `[tools]`: no
//! `[env]`, `[tasks]` or `[daemons]`, so no template or task of the project's is evaluated
//! (any mise command that loads a config evaluates its `[env]` templates). Commands run under
//! the same isolation as every other provider call, pointed at the scratch root.

use crate::error::{io_error, Result};
use crate::lock::Lockfile;
use crate::tool::ToolSpec;
use indexmap::IndexMap;
use std::path::{Path, PathBuf};
use std::process::Command;
use toml::{Table, Value};

/// One tool the scratch configuration names: a provider tool (a service's preset tool for
/// service pins) and its version and allowlisted options.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Pin {
    pub tool: String,
    pub spec: ToolSpec,
}

/// Every release stack.lock pins, as the provider names it: tools under their own names,
/// services under the tool their preset installs (`postgres = "17.6"`), each with the options
/// stack.lock records. Requests that name no release (`system`, `path:`, `ref:`) are left
/// out; identical pins appear once.
pub fn pins(lock: &Lockfile) -> Vec<Pin> {
    let mut out: Vec<Pin> = Vec::new();
    let entries = lock.tools.iter().map(|t| (t.name.as_str(), t)).chain(
        lock.services.iter().filter_map(|s| Some((s.tool.as_deref()?, s))),
    );
    for (tool, entry) in entries {
        if super::mise::unversioned(&entry.resolved) {
            continue;
        }
        let pin = Pin { tool: tool.to_string(), spec: ToolSpec { version: entry.resolved.clone(), options: entry.options.clone() } };
        if !out.contains(&pin) {
            out.push(pin);
        }
    }
    out
}

/// A `[tools]`-only mise configuration. A tool pinned at several versions (two services of
/// one preset at different releases) is written as a list, as mise accepts.
pub fn tools_config(pins: &[Pin]) -> String {
    let mut grouped: IndexMap<&str, Vec<Value>> = IndexMap::new();
    for pin in pins {
        grouped.entry(pin.tool.as_str()).or_default().push(pin.spec.to_toml());
    }
    let tools: Table = grouped
        .into_iter()
        .map(|(tool, mut values)| {
            let value = if values.len() == 1 { values.remove(0) } else { Value::Array(values) };
            (tool.to_string(), value)
        })
        .collect();
    let mut doc = Table::new();
    doc.insert("tools".into(), Value::Table(tools));
    let body = toml::to_string_pretty(&doc).expect("scratch config serializes");
    format!("# Generated by stack for one provider query. Removed afterwards.\n{body}")
}

/// A private provider root, removed on drop.
#[derive(Debug)]
pub struct ScratchRoot {
    dir: tempfile::TempDir,
}

impl ScratchRoot {
    /// A new, empty root at `<cache>/<purpose>/<random>`.
    pub fn create(cache: &Path, purpose: &str) -> Result<Self> {
        let parent = cache.join(purpose);
        std::fs::create_dir_all(&parent).map_err(|e| io_error(parent.display(), e))?;
        let dir = tempfile::Builder::new().prefix("q-").tempdir_in(&parent).map_err(|e| io_error(parent.display(), e))?;
        Ok(Self { dir })
    }

    pub fn path(&self) -> &Path {
        self.dir.path()
    }

    /// Where mise reads the configuration under stack's isolation (as for a project).
    pub fn config_path(&self) -> PathBuf {
        super::mise::output_path(self.path())
    }

    /// Write the `[tools]`-only configuration naming `pins`, replacing any earlier one.
    pub fn write_tools(&self, pins: &[Pin]) -> Result<PathBuf> {
        let path = self.config_path();
        let dir = path.parent().expect("config path has a parent");
        std::fs::create_dir_all(dir).map_err(|e| io_error(dir.display(), e))?;
        std::fs::write(&path, tools_config(pins)).map_err(|e| io_error(path.display(), e))?;
        Ok(path)
    }

    /// `mise <args>` in this root, under the provider isolation pointed at it. The root is
    /// trusted for this command only (`MISE_TRUSTED_CONFIG_PATHS`), so mise neither prompts nor
    /// records trust for a directory about to disappear. Bound it with `process::capture`.
    pub fn command(&self, args: &[&str]) -> Command {
        let mut command = Command::new("mise");
        super::mise::configure_command(&mut command, self.path());
        command
            .args(args)
            .current_dir(self.path())
            .env("MISE_TRUSTED_CONFIG_PATHS", self.path())
            .env("MISE_YES", "1")
            .env("NO_COLOR", "1");
        command
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lock::LockedVersion;
    use crate::tool::OptionValue;

    fn locked(name: &str, tool: Option<&str>, resolved: &str) -> LockedVersion {
        LockedVersion {
            name: name.into(),
            tool: tool.map(Into::into),
            requested: "x".into(),
            resolved: resolved.into(),
            resolved_on: None,
            options: Default::default(),
        }
    }

    #[test]
    fn pins_name_service_tools_and_keep_options() {
        let mut rust = locked("rust", None, "1.93.1");
        rust.options.insert("mr_boxington".into(), OptionValue::Bool(true));
        let lock = Lockfile::new(
            vec![],
            vec![rust, locked("mbx", None, "1.22.0"), locked("node", None, "system"), locked("postgres", None, "17.6")],
            vec![locked("db", Some("postgres"), "17.6"), locked("old", Some("postgres"), "16.4"), locked("x", None, "1")],
        );
        let pins = pins(&lock);
        let names: Vec<String> = pins.iter().map(|p| format!("{}@{}", p.tool, p.spec.version)).collect();
        assert_eq!(names, ["rust@1.93.1", "mbx@1.22.0", "postgres@17.6", "postgres@16.4"]);
        let config = tools_config(&pins);
        let doc: Table = toml::from_str(&config).unwrap();
        assert_eq!(doc.keys().collect::<Vec<_>>(), ["tools"], "{config}");
        assert_eq!(doc["tools"]["rust"]["version"].as_str(), Some("1.93.1"));
        assert_eq!(doc["tools"]["rust"]["mr_boxington"].as_bool(), Some(true));
        assert_eq!(doc["tools"]["mbx"].as_str(), Some("1.22.0"));
        assert_eq!(doc["tools"]["postgres"].as_array().map(Vec::len), Some(2), "{config}");
    }

    #[test]
    fn roots_are_unique_and_removed_on_drop() {
        let cache = tempfile::tempdir().unwrap();
        let a = ScratchRoot::create(cache.path(), "lock").unwrap();
        let b = ScratchRoot::create(cache.path(), "lock").unwrap();
        assert_ne!(a.path(), b.path());
        assert!(a.path().starts_with(cache.path().join("lock")));
        let written = a.write_tools(&[Pin { tool: "jq".into(), spec: ToolSpec::new("1.7.1") }]).unwrap();
        assert_eq!(written, a.path().join(".config/mise/conf.d/stack.toml"));
        let command = a.command(&["ls", "--json"]);
        let env: Vec<(String, String)> = command
            .get_envs()
            .filter_map(|(k, v)| Some((k.to_str()?.to_string(), v?.to_str()?.to_string())))
            .collect();
        let get = |key: &str| env.iter().find(|(k, _)| k == key).map(|(_, v)| v.as_str());
        assert_eq!(get("MISE_TRUSTED_CONFIG_PATHS"), a.path().to_str());
        assert_eq!(get("MISE_OVERRIDE_CONFIG_FILENAMES"), Some(".config/mise/conf.d/stack.toml"));
        assert_eq!(command.get_current_dir(), Some(a.path()));
        let (pa, pb) = (a.path().to_path_buf(), b.path().to_path_buf());
        drop(a);
        drop(b);
        assert!(!pa.exists() && !pb.exists());
    }
}
