//! Scratch provider roots: a private mise configuration that names exact tools and nothing else.
//!
//! Version resolution, artifact locking and skills discovery ask mise about releases without
//! touching the project. Each call gets a root of its own under the cache
//! (`<cache>/<purpose>/<random>/`), removed when the [`ScratchRoot`] is dropped, success or
//! not, so concurrent commands never share one. Its only configuration is `[tools]`: no
//! `[env]`, `[tasks]` or `[daemons]`, so no template or task of the project's is evaluated
//! (any mise command that loads a config evaluates its `[env]` templates). Commands run under
//! the same isolation as every other provider call, pointed at the scratch root.
//!
//! mise links every configuration it loads under `<state>/tracked-configs`, and only `mise
//! prune` removes links whose file is gone. Each [`ScratchRoot::command`] notes the state
//! directory its environment names, and dropping the root removes the links there that point
//! into it, and nothing else. A root whose process is killed before it drops leaves both the
//! root and its links.

use crate::error::{io_error, Result, StackError};
use crate::lock::Lockfile;
use crate::tool::{templated, OptionValue, ToolSpec};
use indexmap::IndexMap;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::Mutex;
use toml::{Table, Value};

/// One tool the scratch configuration names: a provider tool (a service's preset tool for
/// service pins) and its version and allowlisted options.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Pin {
    pub tool: String,
    pub spec: ToolSpec,
}

/// Every release stack.lock pins, as the provider names it: tools under their own names,
/// services under the tool their preset installs (`postgres = "17.6"`), each with the options
/// stack.lock records. Requests that name no release (`system`, `path:`, `ref:`) are left
/// out; identical pins appear once.
pub fn pins(lock: &Lockfile) -> Vec<Pin> {
    let mut out: Vec<Pin> = Vec::new();
    let entries = lock.tools.iter().map(|t| (t.name.as_str(), t)).chain(
        lock.services.iter().filter_map(|s| Some((s.tool.as_deref()?, s))),
    );
    for (tool, entry) in entries {
        if super::mise::unversioned(&entry.resolved) {
            continue;
        }
        let pin = Pin { tool: tool.to_string(), spec: ToolSpec { version: entry.resolved.clone(), options: entry.options.clone() } };
        if !out.contains(&pin) {
            out.push(pin);
        }
    }
    out
}

/// A `[tools]`-only mise configuration. A tool pinned at several versions (two services of
/// one preset at different releases) is written as a list, as mise accepts.
pub fn tools_config(pins: &[Pin]) -> String {
    let mut grouped: IndexMap<&str, Vec<Value>> = IndexMap::new();
    for pin in pins {
        grouped.entry(pin.tool.as_str()).or_default().push(pin.spec.to_toml());
    }
    let tools: Table = grouped
        .into_iter()
        .map(|(tool, mut values)| {
            let value = if values.len() == 1 { values.remove(0) } else { Value::Array(values) };
            (tool.to_string(), value)
        })
        .collect();
    let mut doc = Table::new();
    doc.insert("tools".into(), Value::Table(tools));
    let body = toml::to_string_pretty(&doc).expect("scratch config serializes");
    format!("# Generated by stack for one provider query. Removed afterwards.\n{body}")
}

/// The scratch configuration is trusted, and mise renders tool versions and option strings
/// there as templates (`exec()` included). Manifests refuse template syntax where they are
/// read; this holds for every other way a pin can arrive (a hand-edited stack.lock, a resolver
/// called directly), so no query runs what a pin says.
pub fn check_literal(pins: &[Pin]) -> Result<()> {
    for pin in pins {
        let option = pin.spec.options.iter().find(|(_, v)| matches!(v, OptionValue::String(s) if templated(s)));
        let what = if templated(&pin.tool) {
            "its name".to_string()
        } else if templated(&pin.spec.version) {
            "its version".to_string()
        } else if let Some((key, _)) = option {
            format!("option `{key}`")
        } else {
            continue;
        };
        return Err(StackError::new(
            "invalid_tool",
            format!("{}: {what} must not contain template syntax (`{{{{`, `{{%` or `{{#`); stack does not ask mise about it", pin.tool),
        )
        .hint("tool and service versions and options must be literal; fix the request (or stack.lock, if edited) and run `stack compile`")
        .with_detail(serde_json::json!({ "tool": pin.tool })));
    }
    Ok(())
}

/// A private provider root, removed on drop with the links mise made to it.
#[derive(Debug)]
pub struct ScratchRoot {
    dir: tempfile::TempDir,
    /// mise's `tracked-configs` directories, as the root's commands name them.
    tracked: Mutex<Vec<PathBuf>>,
}

impl ScratchRoot {
    /// A new, empty root at `<cache>/<purpose>/<random>`.
    pub fn create(cache: &Path, purpose: &str) -> Result<Self> {
        let parent = cache.join(purpose);
        std::fs::create_dir_all(&parent).map_err(|e| io_error(parent.display(), e))?;
        // mise compares its ceiling (the root's parent) with the working directory's ancestors
        // by equality, and the working directory is resolved: through a linked cache path
        // (`/tmp` on macOS) the ceiling would never match and mise would search above the root.
        let parent = parent.canonicalize().map_err(|e| io_error(parent.display(), e))?;
        let dir = tempfile::Builder::new().prefix("q-").tempdir_in(&parent).map_err(|e| io_error(parent.display(), e))?;
        Ok(Self { dir, tracked: Mutex::default() })
    }

    pub fn path(&self) -> &Path {
        self.dir.path()
    }

    /// Where mise reads the configuration under stack's isolation (as for a project).
    pub fn config_path(&self) -> PathBuf {
        super::mise::output_path(self.path())
    }

    /// Write the `[tools]`-only configuration naming `pins`, replacing any earlier one. A pin
    /// with template syntax is refused before anything is written (see [`check_literal`]).
    pub fn write_tools(&self, pins: &[Pin]) -> Result<PathBuf> {
        check_literal(pins)?;
        let path = self.config_path();
        let dir = path.parent().expect("config path has a parent");
        std::fs::create_dir_all(dir).map_err(|e| io_error(dir.display(), e))?;
        std::fs::write(&path, tools_config(pins)).map_err(|e| io_error(path.display(), e))?;
        Ok(path)
    }

    /// `mise <args>` in this root, under the provider isolation pointed at it. The root is
    /// trusted for this command only (`MISE_TRUSTED_CONFIG_PATHS`), so mise neither prompts nor
    /// records trust for a directory about to disappear. Bound it with `process::capture`.
    ///
    /// The state directory is read from the command as returned (see [`ScratchRoot`]'s drop);
    /// a caller must not change `MISE_STATE_DIR`, `XDG_STATE_HOME` or `HOME` on it.
    pub fn command(&self, args: &[&str]) -> Command {
        let command = self.untracked(args);
        self.track(&command);
        command
    }

    /// [`ScratchRoot::command`] before its state directory is noted.
    fn untracked(&self, args: &[&str]) -> Command {
        let mut command = Command::new("mise");
        super::mise::configure_command(&mut command, self.path());
        command
            .args(args)
            .current_dir(self.path())
            .env("MISE_TRUSTED_CONFIG_PATHS", self.path())
            .env("MISE_YES", "1")
            .env("NO_COLOR", "1");
        command
    }

    /// Note where `command`'s mise keeps tracking links: what the command sets or removes,
    /// otherwise what stack inherited.
    fn track(&self, command: &Command) {
        let var = |key: &str| match command.get_envs().find(|(k, _)| *k == key) {
            Some((_, value)) => value.and_then(|v| v.to_str()).map(str::to_string),
            None => std::env::var(key).ok(),
        };
        let Some(dir) = tracked_configs(self.path(), var) else { return };
        let mut tracked = self.tracked.lock().unwrap_or_else(|e| e.into_inner());
        if !tracked.contains(&dir) {
            tracked.push(dir);
        }
    }
}

impl Drop for ScratchRoot {
    fn drop(&mut self) {
        // The directory itself is removed after this, when `dir` is dropped.
        let tracked = self.tracked.get_mut().unwrap_or_else(|e| e.into_inner());
        for dir in tracked.iter() {
            unlink_into(dir, self.dir.path());
        }
    }
}

/// mise's `tracked-configs` directory for a command run in `cwd` that sees `var`, as mise
/// finds it: `MISE_STATE_DIR`, else `$XDG_STATE_HOME/mise`, else `~/.local/state/mise`. An
/// empty value counts as unset, a leading `~` is the home directory, and a relative path is
/// read from the working directory.
fn tracked_configs(cwd: &Path, var: impl Fn(&str) -> Option<String>) -> Option<PathBuf> {
    let set = |key: &str| var(key).filter(|v| !v.is_empty());
    let home = set("HOME").map(|h| cwd.join(h)).or_else(std::env::home_dir);
    let path = |value: String| -> Option<PathBuf> {
        let path = match value.strip_prefix('~') {
            Some(rest) if rest.is_empty() || rest.starts_with('/') => home.clone()?.join(rest.trim_start_matches('/')),
            _ => PathBuf::from(value),
        };
        Some(cwd.join(path))
    };
    let state = match set("MISE_STATE_DIR") {
        Some(dir) => path(dir)?,
        None => match set("XDG_STATE_HOME") {
            Some(dir) => path(dir)?.join("mise"),
            None => home?.join(".local/state/mise"),
        },
    };
    Some(state.join("tracked-configs"))
}

/// Remove the links in `tracked` that point into `root`. Regular files, directories and links
/// to anything else are left alone.
fn unlink_into(tracked: &Path, root: &Path) {
    let Ok(entries) = std::fs::read_dir(tracked) else { return };
    for entry in entries.flatten() {
        if !entry.file_type().is_ok_and(|t| t.is_symlink()) {
            continue;
        }
        // mise writes absolute targets; a relative one is read from the link's directory.
        if std::fs::read_link(entry.path()).is_ok_and(|target| tracked.join(target).starts_with(root)) {
            let _ = std::fs::remove_file(entry.path());
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lock::LockedVersion;
    use crate::tool::OptionValue;

    fn locked(name: &str, tool: Option<&str>, resolved: &str) -> LockedVersion {
        LockedVersion {
            name: name.into(),
            tool: tool.map(Into::into),
            requested: "x".into(),
            resolved: resolved.into(),
            resolved_on: None,
            options: Default::default(),
        }
    }

    #[test]
    fn pins_name_service_tools_and_keep_options() {
        let mut rust = locked("rust", None, "1.93.1");
        rust.options.insert("mr_boxington".into(), OptionValue::Bool(true));
        let lock = Lockfile::new(
            vec![],
            vec![rust, locked("mbx", None, "1.22.0"), locked("node", None, "system"), locked("postgres", None, "17.6")],
            vec![locked("db", Some("postgres"), "17.6"), locked("old", Some("postgres"), "16.4"), locked("x", None, "1")],
        );
        let pins = pins(&lock);
        let names: Vec<String> = pins.iter().map(|p| format!("{}@{}", p.tool, p.spec.version)).collect();
        assert_eq!(names, ["rust@1.93.1", "mbx@1.22.0", "postgres@17.6", "postgres@16.4"]);
        let config = tools_config(&pins);
        let doc: Table = toml::from_str(&config).unwrap();
        assert_eq!(doc.keys().collect::<Vec<_>>(), ["tools"], "{config}");
        assert_eq!(doc["tools"]["rust"]["version"].as_str(), Some("1.93.1"));
        assert_eq!(doc["tools"]["rust"]["mr_boxington"].as_bool(), Some(true));
        assert_eq!(doc["tools"]["mbx"].as_str(), Some("1.22.0"));
        assert_eq!(doc["tools"]["postgres"].as_array().map(Vec::len), Some(2), "{config}");
    }

    #[test]
    fn pins_with_template_syntax_are_refused_before_anything_is_written() {
        let cache = tempfile::tempdir().unwrap();
        let root = ScratchRoot::create(cache.path(), "resolve").unwrap();
        let payload = |open: &str, close: &str| format!("{open} exec(command='touch x') {close}");
        let with_option = |value: String| {
            let mut spec = ToolSpec::new("1.39.0");
            spec.options.insert("identity".into(), OptionValue::String(value));
            spec
        };
        for (open, close) in [("{{", "}}"), ("{%", "%}"), ("{#", "#}")] {
            for (pin, what) in [
                (Pin { tool: "postgres".into(), spec: ToolSpec::new(payload(open, close)) }, "its version"),
                (Pin { tool: "fnox".into(), spec: with_option(payload(open, close)) }, "option `identity`"),
                (Pin { tool: payload(open, close), spec: ToolSpec::new("1") }, "its name"),
            ] {
                // A literal pin beside it does not make the query acceptable.
                let pins = [Pin { tool: "jq".into(), spec: ToolSpec::new("1.7.1") }, pin];
                let e = root.write_tools(&pins).unwrap_err();
                assert_eq!(e.code, "invalid_tool", "{pins:?}");
                assert!(e.message.contains(&format!("{what} must not contain template syntax")), "{}", e.message);
                assert!(!root.config_path().exists() && !root.path().join(".config").exists(), "{pins:?}");
            }
        }
        // `{` and `}` alone are not template syntax.
        root.write_tools(&[Pin { tool: "jq".into(), spec: ToolSpec::new("1.7.1") }, Pin { tool: "fnox".into(), spec: with_option("a{b}".into()) }]).unwrap();
        assert!(root.config_path().exists());
    }

    #[test]
    fn roots_are_unique_and_removed_on_drop() {
        let cache = tempfile::tempdir().unwrap();
        let a = ScratchRoot::create(cache.path(), "lock").unwrap();
        let b = ScratchRoot::create(cache.path(), "lock").unwrap();
        assert_ne!(a.path(), b.path());
        assert!(a.path().starts_with(cache.path().canonicalize().unwrap().join("lock")));
        let written = a.write_tools(&[Pin { tool: "jq".into(), spec: ToolSpec::new("1.7.1") }]).unwrap();
        assert_eq!(written, a.path().join(".config/mise/conf.d/stack.toml"));
        let command = a.command(&["ls", "--json"]);
        let env: Vec<(String, String)> = command
            .get_envs()
            .filter_map(|(k, v)| Some((k.to_str()?.to_string(), v?.to_str()?.to_string())))
            .collect();
        let get = |key: &str| env.iter().find(|(k, _)| k == key).map(|(_, v)| v.as_str());
        assert_eq!(get("MISE_TRUSTED_CONFIG_PATHS"), a.path().to_str());
        assert_eq!(get("MISE_OVERRIDE_CONFIG_FILENAMES"), Some(".config/mise/conf.d/stack.toml"));
        assert_eq!(command.get_current_dir(), Some(a.path()));
        let (pa, pb) = (a.path().to_path_buf(), b.path().to_path_buf());
        drop(a);
        drop(b);
        assert!(!pa.exists() && !pb.exists());
    }

    #[test]
    fn the_tracking_directory_is_where_mise_keeps_it() {
        let cwd = Path::new("/work/root");
        let at = |vars: &[(&str, &str)]| {
            let vars: Vec<(String, String)> = vars.iter().map(|(k, v)| (k.to_string(), v.to_string())).collect();
            tracked_configs(cwd, |key| vars.iter().find(|(k, _)| k == key).map(|(_, v)| v.clone())).unwrap()
        };
        let home = ("HOME", "/home/u");
        assert_eq!(at(&[home, ("XDG_STATE_HOME", "/x"), ("MISE_STATE_DIR", "/s")]), Path::new("/s/tracked-configs"));
        assert_eq!(at(&[home, ("MISE_STATE_DIR", "rel")]), Path::new("/work/root/rel/tracked-configs"));
        assert_eq!(at(&[home, ("MISE_STATE_DIR", "~/st")]), Path::new("/home/u/st/tracked-configs"));
        assert_eq!(at(&[home, ("MISE_STATE_DIR", ""), ("XDG_STATE_HOME", "/x")]), Path::new("/x/mise/tracked-configs"));
        assert_eq!(at(&[home, ("XDG_STATE_HOME", "relx")]), Path::new("/work/root/relx/mise/tracked-configs"));
        assert_eq!(at(&[home, ("XDG_STATE_HOME", "")]), Path::new("/home/u/.local/state/mise/tracked-configs"));
        assert_eq!(at(&[("HOME", "relhome")]), Path::new("/work/root/relhome/.local/state/mise/tracked-configs"));
    }

    /// A command whose mise keeps its state in `state`, noted by `root` as `command` does.
    fn tracked_command(root: &ScratchRoot, state: &Path) -> Command {
        let mut command = root.untracked(&["ls", "--json"]);
        command.env("MISE_STATE_DIR", state);
        root.track(&command);
        command
    }

    #[test]
    fn dropping_a_root_removes_only_the_links_into_it() {
        let (cache, state, project) = (tempfile::tempdir().unwrap(), tempfile::tempdir().unwrap(), tempfile::tempdir().unwrap());
        let tracked = state.path().join("tracked-configs");
        std::fs::create_dir_all(&tracked).unwrap();
        let (a, b) = (ScratchRoot::create(cache.path(), "lock").unwrap(), ScratchRoot::create(cache.path(), "lock").unwrap());
        // Commands run at once from one root, as skills discovery does, note the directory once.
        std::thread::scope(|scope| {
            for _ in 0..4 {
                scope.spawn(|| tracked_command(&a, state.path()));
            }
        });
        tracked_command(&b, state.path());
        assert_eq!(*a.tracked.lock().unwrap(), std::slice::from_ref(&tracked));
        let link = |name: &str, target: &Path| std::os::unix::fs::symlink(target, tracked.join(name)).unwrap();
        link("owned", &a.config_path());
        link("owned-dir", a.path());
        link("sibling", &b.config_path());
        // A path that only shares the root's name as a prefix, a removed root of another run
        // (left for `mise prune`), the user's project, and a link once into the root, retargeted.
        link("prefix", Path::new(&format!("{}x/.config/mise/conf.d/stack.toml", a.path().display())));
        link("killed", &a.path().with_file_name("q-gone").join(".config/mise/conf.d/stack.toml"));
        link("project", &project.path().join("mise.toml"));
        link("retargeted", &a.config_path());
        std::fs::remove_file(tracked.join("retargeted")).unwrap();
        link("retargeted", &project.path().join("mise.toml"));
        std::fs::write(tracked.join("regular"), a.config_path().to_string_lossy().as_bytes()).unwrap();
        // Trust mise records elsewhere in its state is not tracking.
        std::fs::create_dir_all(state.path().join("trusted-configs")).unwrap();
        std::os::unix::fs::symlink(a.config_path(), state.path().join("trusted-configs/user")).unwrap();
        let names = || {
            let mut left: Vec<String> = std::fs::read_dir(&tracked).unwrap().map(|e| e.unwrap().file_name().to_string_lossy().into_owned()).collect();
            left.sort();
            left
        };
        let a_path = a.path().to_path_buf();
        drop(a);
        assert!(!a_path.exists());
        assert_eq!(names(), ["killed", "prefix", "project", "regular", "retargeted", "sibling"]);
        assert!(state.path().join("trusted-configs/user").symlink_metadata().is_ok());
        drop(b);
        assert_eq!(names(), ["killed", "prefix", "project", "regular", "retargeted"]);
    }

    #[test]
    fn a_root_that_ran_no_command_touches_no_tracking() {
        let (cache, state) = (tempfile::tempdir().unwrap(), tempfile::tempdir().unwrap());
        let root = ScratchRoot::create(cache.path(), "resolve").unwrap();
        let tracked = state.path().join("tracked-configs");
        std::fs::create_dir_all(&tracked).unwrap();
        std::os::unix::fs::symlink(root.config_path(), tracked.join("noted-elsewhere")).unwrap();
        drop(root);
        assert!(tracked.join("noted-elsewhere").symlink_metadata().is_ok());
    }

    /// Against the mise named by `STACK_TEST_MISE`: the links it makes for concurrent roots in
    /// one cache land where the root looks, and each root's drop removes its own.
    #[test]
    fn real_mise_tracking_links_are_removed_with_their_roots() {
        let Some(mise) = std::env::var_os("STACK_TEST_MISE").map(PathBuf::from) else {
            eprintln!("skipped: set STACK_TEST_MISE to a mise binary");
            return;
        };
        let (cache, work) = (tempfile::tempdir().unwrap(), tempfile::tempdir().unwrap());
        let state = work.path().join("mise-state");
        let tracked = state.join("tracked-configs");
        let path = std::env::join_paths(std::iter::once(mise.parent().unwrap().to_path_buf()).chain(std::env::split_paths(&std::env::var_os("PATH").unwrap_or_default()))).unwrap();
        let run = |root: &ScratchRoot| {
            root.write_tools(&[Pin { tool: "jq".into(), spec: ToolSpec::new("1.7.1") }]).unwrap();
            let mut command = tracked_command(root, &state);
            command.env("PATH", &path).env("MISE_DATA_DIR", work.path().join("data")).env("MISE_CACHE_DIR", work.path().join("cache"));
            let out = command.output().unwrap();
            assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
        };
        let (a, b) = (ScratchRoot::create(cache.path(), "skills").unwrap(), ScratchRoot::create(cache.path(), "skills").unwrap());
        std::thread::scope(|scope| {
            scope.spawn(|| run(&a));
            run(&b);
        });
        let targets = || -> Vec<PathBuf> {
            std::fs::read_dir(&tracked).unwrap().map(|e| std::fs::read_link(e.unwrap().path()).unwrap()).collect()
        };
        assert_eq!(*a.tracked.lock().unwrap(), std::slice::from_ref(&tracked));
        let left = targets();
        assert!(left.contains(&a.config_path()) && left.contains(&b.config_path()), "{left:?}");
        let b_config = b.config_path();
        drop(a);
        assert_eq!(targets(), [b_config]);
        drop(b);
        assert_eq!(targets(), Vec::<PathBuf>::new());
        assert!(!state.join("trusted-configs").exists(), "the roots are trusted per command, never recorded");
    }
}
